# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Yilun Chen
title: Machine Learning Researcher & Engineer
email: yilunc0127@gmail.com
# phone:
website:  https://www.researchgate.net/profile/Yilun_Chen7/research

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: yilun-alice-chen
github_username:
twitter_username:
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username:
# flickr_username: jekyll
instagram_username:
# xing_username: jekyll
pinterest_username:
youtube_username:
googleplus_username:
# orcid_username: 0000-0000-0000-0000
Researchgate_username:

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: assets/photo.png
about_content: | # this will include new lines to allow paragraphs

      I'm currently a Research Engineer in Optimization and Data Science, with passion in large-scale machine learning models and scalable data-driven decision-making leveraged in cloud computing. My career goal is to combine the state-of-art in modeling with the science and engineering behind scalable machine learning system development and to solve industrial problem with higher-order of efficiency.

      My research interest is majorly in the application development in NLP & Graph Network analysis, and Auto Machine Learning System and Deep Learning Architecture. I also have theoretical knowledge experience of Bayesian Statistics, Multi-Armed Bandit Problems, Optimization and Game Theory.

      Apart from my research time, I am equipping myself with software development and cloud computing skills. For example, I am taking specialities from Coursera, such as Data Engineering, Big Data on GCP, TensorFlow: Data and Deployment, Advanced Machine Learning with TensorFlow on Google Cloud Platform, Cloud Architecture with Google Cloud and AWS Foundation. I have some hands-on experience on software development using Java, specifically in developing Android APP and Website APP.

      Technical Skills:
        - **Computer Languages:** Python, R, SQL, C++, Java, Matlab
        - **Big Data Skills:** Spark, Hive, AWS, Google Cloud, Azure, Databricks, Docker, Git
        - **Relevant Packages:** Scikit-learn, XGBoost, PySpark, Tensorflow, PyMC3, Flask, Bokeh
#   Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
#
#   You can even add paragraphs by using empty lines like this and add anything else markdown supports such as

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Publication and Machine Learning Projects
more_content: | # this will include new lines to allow paragraphs
        **CNN on CFD static flow images**
        http://meetings.aps.org/Meeting/DFD19/Session/NP05.172
        https://event.asme.org/IMECE
profile_image: assets/cfd.png
        **AutoML on Graph Neural Network**

        **Knowledge Graph in NLP**




# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
